import { Member } from '@src/types'

export const members: Member[] = [
  {
    id: 'kj',
    name: '麻野耕司',
    role: 'CEO',
    bio: 'CEO',
    avatarSrc: '/avatars/kj.jpg',
    sources: ['https://note.com/kojiasano1103/rss'],
    includeUrlRegex: '',
    twitterUsername: 'asanokoji',
    githubUsername: '',
    websiteUrl: '',
  },
  {
    id: 'mayah',
    name: 'mayah',
    role: 'CTO',
    bio: 'CTO',
    avatarSrc: '/avatars/mayah.jpg',
    sources: ['https://mayah.jp/index.xml'],
    includeUrlRegex: '',
    twitterUsername: 'mayahjp',
    githubUsername: 'mayah',
    websiteUrl: 'https://mayah.jp',
  },
  {
    id: 'yoshiko',
    name: 'よしこ',
    role: 'Frontend',
    bio: 'Frontend Engineer',
    avatarSrc: '/avatars/yoshiko.png',
    sources: ['https://zenn.dev/yoshiko/feed', 'https://yoshiko.hatenablog.jp/feed'],
    includeUrlRegex: '',
    twitterUsername: 'yoshiko_pg',
    githubUsername: 'yoshiko-pg',
    websiteUrl: '',
  },
  {
    id: 'zawakin',
    name: 'zawakin',
    role: 'Backend',
    bio: 'Backend Engineer',
    avatarSrc: '/avatars/zawakin.jpg',
    sources: [
      'https://www.zawawahoge.com/index.xml',
      'https://zenn.dev/zawawahoge/feed',
      'https://qiita.com/zawawahoge/feed',
    ],
    includeUrlRegex: '',
    twitterUsername: 'zawawahoge',
    githubUsername: 'zawawahoge',
    websiteUrl: 'https://www.zawawahoge.com',
  },
  {
    id: 'yudoufu',
    name: 'yudoufu',
    role: 'Infra',
    bio: 'Infra Engineer',
    avatarSrc: '/avatars/yudoufu.png',
    sources: ['https://yudoufu.hatenablog.jp/feed', 'https://zenn.dev/yudoufu/feed'],
    includeUrlRegex: '',
    twitterUsername: 'yudoufu',
    githubUsername: 'yudoufu',
    websiteUrl: '',
  },
  {
    id: 'aoshi',
    name: 'aoshi',
    role: 'Frontend',
    bio: 'Frontend Engineer',
    avatarSrc: '/avatars/aoshi.png',
    sources: ['https://note.com/deepblue_will/rss', 'https://zenn.dev/deepblue_will/feed'],
    includeUrlRegex: '',
    twitterUsername: 'deepblue_will',
    githubUsername: 'deepblue-will',
    websiteUrl: '',
  },
  {
    id: 'sadakoa',
    name: 'sadakoa',
    role: 'Designer',
    bio: 'Designer',
    avatarSrc: '/avatars/sadakoa.jpg',
    sources: ['https://note.com/sadako_a_/rss'],
    includeUrlRegex: '',
    twitterUsername: 'sadako_a_',
    githubUsername: '',
    websiteUrl: 'https://mamorukijima.com/',
  },
  {
    id: 'nannichi',
    name: '南日政俊',
    role: 'BizDev',
    bio: 'Business Development',
    avatarSrc: '/avatars/nannichi.jpg',
    sources: ['https://note.com/masatoshi_228/rss'],
    includeUrlRegex: '',
    twitterUsername: 'MTNN_228',
    githubUsername: '',
    websiteUrl: '',
  },
  {
    id: 'yackrru',
    name: 'yackrru',
    role: 'Backend',
    bio: 'Backend Engineer',
    avatarSrc: '/avatars/yackrru.jpg',
    sources: [
      'https://qiita.com/yackrru/feed',
    ],
    includeUrlRegex: '',
    twitterUsername: 'yackrru',
    githubUsername: 'yackrru',
    websiteUrl: '',
  },
]
